### PR TITLE
Add provides variable

### PR DESCRIPTION
**Pull request by abouvier**
Allow to mix a specific git package with the stable Papirus meta-package.

### CODE REVIEW

**Comment by FadeMind** [comment]
@abouvier Provides variable is useless here. Meta package store names of optional packages only. I secured older names of papirus packages against conflicts and this is fine for me. Here is copy of 42 packages for AUR and 19 for KaOS.

**Comment by abouvier** [comment]
@FadeMind It's not useless :p
Currently I can't install `papirus` and then replace, e.g., `papirus-sddm-theme` by `papirus-sddm-theme-git`. Pacman will complain about removing one of `papirus` dependency (because the conflicts option will force pacman to remove `papirus-sddm-theme`). But with the provides option, each git package can replace the stable one.

**Comment by FadeMind** [comment]
I don't want mix git and non git packages in meta. Advanced users can just install needed packages without install meta package. The same results.

**Comment by prettyv** [comment]
I agree with the intention of @abouvier here - quoting from the [VCS PKGBUILD guidelines](https://wiki.archlinux.org/index.php/VCS_PKGBUILD_Guidelines):

> Include what the package conflicts with and provides (e.g. for fluxbox-gitAUR: conflicts=('fluxbox') and provides=('fluxbox')).

Adding a provides line to the -git PKGBUILDS is very common and arguably expected behaviour. I see no good reason to wilfully block the possibility to replace a dependency of a meta-package with its '-git'-equivalent when it doesn't really functionally conflict. (Besides, AUR packages being officially unsupported, using a PKGBUILD makes one an "advanced" user by default anyway. ;))

**Pull request closed without merging**
